#!/bin/bash

# ANSI
# format: \033[#(;#)m
# forground colors: (30-37)
# background colors: (40-47)
# attribs:
#   0 = normal
#   1 = bold
#   4 = underline
#   5 = blink
#   7 = invert
#   8 = invisible (?)
#
#

# Forground colors
LBLACK=$(printf   "\033[0;30m")
BLACK=$(printf    "\033[1;30m")
LRED=$(printf     "\033[0;31m")
RED=$(printf      "\033[1;31m")
LGREEN=$(printf   "\033[0;32m")
GREEN=$(printf    "\033[1;32m")
LYELLOW=$(printf  "\033[0;33m")
YELLOW=$(printf   "\033[1;33m")
LBLUE=$(printf    "\033[0;34m")
BLUE=$(printf     "\033[1;34m")
LMAGENTA=$(printf "\033[0;35m")
MAGENTA=$(printf  "\033[1;35m")
LCYAN=$(printf    "\033[0;36m")
CYAN=$(printf     "\033[1;36m")
LWHITE=$(printf   "\033[0;37m")
WHITE=$(printf    "\033[1;37m")
RESET_COLOR=$(printf "\033[m")

#echo "set up colors"
