tap 'homebrew/cask-fonts'

brew 'ag'
brew 'asdf'
# Big Sur Erlang fix
brew 'autoconf@2.69', link: true, overwrite: true
brew 'autojump'
brew 'bat'
brew 'cheat'
brew 'exa'
brew 'fd'
brew 'freetds'
brew 'fzf'
brew 'getantibody/tap/antibody'
brew 'git'
brew 'gpg'
brew 'postgresql'
brew 'python'
brew 'ripgrep'
brew "the_silver_searcher"
brew 'tree'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']
brew 'vim'
brew 'zsh'

cask 'keybase'
cask 'font-hack-nerd-font'
