#!/bin/bash

export GIT_PAGER=cat;

if [ $# -eq '0' ]
then
    echo >&2 no command given
    exit 1
fi

function doGitCmd {
    local dir=$1
    shift # pop directory argument
    source ~/.bash/colors
    cd "$dir"
    echo -e "${MAGENTA}${dir}${RESET_COLOR}"
    git "$@"
    cd - >/dev/null # switch back to old directory
}

# locate each git repository, print the pwd and execute given git command within
git find-all | while read LINE
do
    doGitCmd "$LINE" "$@"
done

#export -f doGitCmd
#git find-all -0 | \
#        xargs -0 -n 1 -I '{}' bash -c 'doGitCmd "$@"' - '{}' "$@"

